### ISSUE TITLE
ExceptionInInitializerError cause by NullPointer exception on SLF4J

### ISSUE THREAD

**Issue by xuai99** [nomis/slf4j-android#182]
`
  "crashReason": "java.lang.ExceptionInInitializerError",
  "Back Trace": [
    "at com.NetworkApplication.JMDNS.service.core.managers.jettyManager.JettyManager$StartJettyThread.run(JettyManager.java:702)",
    "at java.lang.Thread.run(Thread.java:1012)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.println(java.lang.String)' on a null object reference",
    "at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:381)",
    "at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:376)",
    "at org.slf4j.impl.SimpleLogger.formatAndLog(SimpleLogger.java:430)",
    "at org.slf4j.impl.SimpleLogger.info(SimpleLogger.java:562)",
    "at org.eclipse.jetty.util.log.Slf4jLog.info(Slf4jLog.java:77)",
    "at org.eclipse.jetty.util.log.Log.initialized(Log.java:170)",
    "at org.eclipse.jetty.util.log.Log.getLogger(Log.java:278)",
    "at org.eclipse.jetty.util.log.Log.getLogger(Log.java:267)",
    "at org.eclipse.jetty.util.component.AbstractLifeCycle.<clinit>(AbstractLifeCycle.java:36)",
    "... 2 more"
  ]
}` 

My android project is pointing to "implementation  ('org.slf4j:slf4j-simple:1.7.9')" do i have to upgrade to a latest version to prevent this issue? if yes what version should i upgrade to?

**Comment by nomis** [comment]
This project is `uk.uuid.slf4j:slf4j-android`, not `org.slf4j:slf4j-simple`.

**Comment by xuai99** [comment]
okay sorry
